apiVersion: v1
kind: Service
metadata:
  name: feathercoin
  namespace: default
spec:
  ports:
    - name: p2p
      port: 9336
      targetPort: 9336
    - name: rpc
      port: 9337
      targetPort: 9337
    - name: testnet-p2p
      port: 19336
      targetPort: 19336
    - name: testnet-rpc
      port: 19337
      targetPort: 19337      
  selector:
    service: feathercoin
  type: LoadBalancer
  externalTrafficPolicy: Local
